### ISSUE TITLE
DBAction does not handle exceptions well

### ISSUE THREAD

**Issue by v6ak** [playframework/play-slick#218]
When I write a code that throws an exception in the Action, it shows a standard error page in Play and logs the error:

	def trickyErr = Action{
		Ok(Txt(???))
	}

However, when I use DBAction instead, it does not log anything in production and it does not show any error message. It just hangs when trying to load:

	def trickyErr = DBAction{
		Ok(Txt(???))
	}

When running in dev mode, it is still not ideal, but the error is written to the console:

	Exception in thread "slick.db.execution.context-1" scala.NotImplementedError: an implementation is missing
		at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
		at controllers.Application$$anonfun$trickyErr$1.apply(Application.scala:87)
		at controllers.Application$$anonfun$trickyErr$1.apply(Application.scala:87)
		at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
		at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Exception in thread "slick.db.execution.context-3" scala.NotImplementedError: an implementation is missing
		at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
		at controllers.Application$$anonfun$trickyErr$1.apply(Application.scala:87)
		at controllers.Application$$anonfun$trickyErr$1.apply(Application.scala:87)
		at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
		at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

When running in production mode, I can't see such error in the log. (When I use just Action instead, I can see the Exception in the log.)

This is very painful when some error happens only in the production mode.

## Environment

* Ubuntu 12.04 (dev), Debian 7.7 (prod), both up-to-date
* Oracle Java 8 (dev), Oracle Java 7 (prod)
* Play 2.3.6
* Play-Slick 0.8.0 or 0.7.0 (tested both of them)

## Workaround

Don't use DBAction. Use standard Action (or something similar) with `DB.withSession{ implicit session => ... }`

**Comment by dotta** [comment]
I'm closing this since play-slick 1.0.0 has removed the need of using `DBAction` (or any other custom abstraction). Using play-slick 1.0.0 boils down to use stock Play 2.4 with Slick 3. Older releases of play-slick are no longer maintained.
