### ISSUE TITLE
Error with sbt - Modules were resolved with conflicting cross-version suffixes

### ISSUE THREAD

**Issue by josephpconley** [playframework/play-slick#228]
Did a fresh clone from the master branch on a Windows box with sbt 0.13.7 installed.  Simply running `sbt` at the root of the project results in the following error message:

	[info] Loading global plugins from C:\Users\josep_000\.sbt\0.13\plugins
	[info] Loading project definition from C:\workspace\playframework\play-slick\project
	[error] Modules were resolved with conflicting cross-version suffixes in {file:/C:/workspace/playframework/play-slick/project/}play-slick-build:
	[error]    net.databinder:dispatch-core _2.9.1, _2.10
	[error]    net.databinder:dispatch-http _2.9.1, _2.10
	[error]    net.databinder:dispatch-futures _2.9.1, _2.10
	java.lang.RuntimeException: Conflicting cross-version suffixes in: net.databinder:dispatch-core, net.databinder:dispatch-http, net.databinder:dispatch-futures
		at scala.sys.package$.error(package.scala:27)
		at sbt.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:46)
		at sbt.ConflictWarning$.apply(ConflictWarning.scala:32)
		at sbt.Classpaths$$anonfun$66.apply(Defaults.scala:1128)
		at sbt.Classpaths$$anonfun$66.apply(Defaults.scala:1124)
		at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
		at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
		at sbt.std.Transform$$anon$4.work(System.scala:63)
		at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
		at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
		at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
		at sbt.Execute.work(Execute.scala:235)
		at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
		at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
		at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
		at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
		at java.util.concurrent.FutureTask.run(FutureTask.java:166)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
		at java.util.concurrent.FutureTask.run(FutureTask.java:166)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
		at java.lang.Thread.run(Thread.java:722)
	[error] (*:update) Conflicting cross-version suffixes in: net.databinder:dispatch-core, net.databinder:dispatch-http, net.databinder:dispatch-futures
	Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

I thought the `sbt-pgp` plugin version might be the culprit per https://github.com/softprops/ls/issues/71 but that doesn't seem to be the case.  Anyone else run into this issue?

**Comment by josephpconley** [comment]
`sbt-pgp` was the culprit, I had a previous version declared in my global `plugins.sbt`.  Sorry for the noise.
