### ISSUE TITLE
java.lang.InstantiationException: play.api.Configuration

### ISSUE THREAD

**Issue by nermin** [playframework/play-slick#254]
play v2.4.0-RC3
play-slick v1.0.0-RC2

The exception below is caused by this line:
`lazy val dbConfig = DatabaseConfigProvider.get[RelationalProfile](Play.current)`

From the stacktrace it looks like a nullary constructor is missing from `play.api.Configuration`, but I might be missing something.

```
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] play.api.Play$ - Application started (Dev)
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
java.lang.InstantiationException: play.api.Configuration
	at java.lang.Class.newInstance(Class.java:423) ~[na:1.8.0_25]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.6.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
Caused by: java.lang.NoSuchMethodException: play.api.Configuration.<init>()
	at java.lang.Class.getConstructor0(Class.java:3074) ~[na:1.8.0_25]
	at java.lang.Class.newInstance(Class.java:408) ~[na:1.8.0_25]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.6.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
[error] application - 

! @6m6ff9lkj - Internal server error, for (POST) [/login] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InstantiationException: play.api.Configuration]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [play-netty-server_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.6.jar:na]
Caused by: java.lang.InstantiationException: play.api.Configuration
	at java.lang.Class.newInstance(Class.java:423) ~[na:1.8.0_25]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.6.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
Caused by: java.lang.NoSuchMethodException: play.api.Configuration.<init>()
	at java.lang.Class.getConstructor0(Class.java:3074) ~[na:1.8.0_25]
	at java.lang.Class.newInstance(Class.java:408) ~[na:1.8.0_25]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.6.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.0-RC3.jar:2.4.0-RC3]
```

**Comment by jroper** [comment]
Are you using compile time DI?

**Comment by nermin** [comment]
Yes.

**Comment by jroper** [comment]
In which case, you shouldn't/can't rely on `Play.current` - presumably since you've chosen to use compile time DI, you prefer your dependencies to be wired at compile time, but if you use `Play.current` at all, then that's going to look up dependencies at runtime, so when `DatabaseConfigProvider` needs a `Configuration` object, it looks into the runtime injector from `Play.current` to find it, which for a compile time DI application, since there is no runtime injector, just does a `newInstance`.

What you probably want to use is [`SlickComponents`](https://www.playframework.com/documentation/2.4.0-RC3/api/scala/index.html#play.api.db.slick.SlickComponents), which will give you a [`SlickApi`](https://www.playframework.com/documentation/2.4.0-RC3/api/scala/index.html#play.api.db.slick.SlickApi), which will give you access to a Slick `DatabaseConfig` from the `dbConfig` methods.

**Comment by nermin** [comment]
@jroper Thank you very much for your answer. It would be great if what you explained here, is also mentioned on [Using Play Slick page](https://www.playframework.com/documentation/2.4.x/PlaySlick), under *Usage* section.
