### ISSUE TITLE
If Database is down Slick will prevent the Server from starting

### ISSUE THREAD

**Issue by schmitch** [playframework/play-slick#275]
Hello, currently it's not a good practice to let the server fail any time due to a java.sql.SQLTimeoutException.
I mean when a SQL Server is running in Master -> Slave while the Master got killed and the slave is trying to be the new Master the application will fail even when the database is offline for a small amount of time.

```
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: Oops, cannot start the server.
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: java.sql.SQLTimeoutException: Timeout after 1001ms of waiting for a connection.
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: at slick.jdbc.HikariCPJdbcDataSource.createConnection(JdbcDataSource.scala:131)
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394)
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:394)
Jun 10 10:22:50 loki1 envisia-erp-loki[2244]: at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:54)
```

**Comment by marcospereira** [comment]
This is more related to hikaricp than to slick. You can configure HikariCP to not fail fast when starting. From HikariCP docs:

> `initializationFailFast`
>
> This property controls whether the pool will "fail fast" if the pool cannot be seeded with initial connections successfully. If you want your application to start even when the database is down/unavailable, set this property to false. 
>
> **Default: true**

**Comment by schmitch** [comment]
so it's slick.dbs.default.db. initializationFailFast or just slick.dbs.default.initializationFailFast?

**Comment by dotta** [comment]
It's `slick.dbs.default.db.initializationFailFast`

**Comment by marcospereira** [comment]
@schmitch can we close this?

**Comment by schmitch** [comment]
yes ty

**Comment by huntc** [comment]
I'm still getting an error, despite having the `initializationFailFast` set to `no` (I'm using a new data source here, but I don't *think* that's the issue):

```
slick.dbs.default = {
  driver = "slick.driver.PostgresDriver$"
  db     = {
    dataSourceClass        = db.ProxyDataSource
    initializationFailFast = no
    properties = {
      serviceName = customerdb
      driver      = org.postgresql.Driver
      url         = "jdbc:postgresql://{host}:{port}/customerdb"
      localHost   = "127.0.0.1"
      localPort   = 5432
      user        = postgres
      password    = "mysecretpassword"
    }
  }
}
```

Error:

```
Oops, cannot start the server.
java.sql.SQLTimeoutException: Timeout after 1004ms of waiting for a connection.
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
	at slick.jdbc.HikariCPJdbcDataSource.createConnection(JdbcDataSource.scala:131)
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394)
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:394)
	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:54)
	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:56)
	at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:119)
	at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:97)
	at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:112)
	at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:77)
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:50)
	at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:98)
	at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
	at scala.collection.immutable.Stream.foreach(Stream.scala:594)
	at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
	at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:149)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:44)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at com.typesafe.conductr.bundlelib.play.ConductRApplicationLoader.load(ConductRApplicationLoader.scala:20)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:239)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:41)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at slick.jdbc.ProxyDataSource.getConnection(ProxyDataSource.scala:106)
	at slick.jdbc.ProxyDataSource.getConnection(ProxyDataSource.scala:72)
	at slick.jdbc.ProxyDataSource.getConnection(ProxyDataSource.scala:60)
	at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:438)
	at com.zaxxer.hikari.pool.BaseHikariPool$1.run(BaseHikariPool.java:413)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:121)
	... 20 more
```

Any further ideas?

**Comment by marcospereira** [comment]
@huntc I don't know if you can set it directly to `no` or if you need to represent it as a String (like `"no"`). Can you try with a `false` value and tells us if it works?

**Comment by huntc** [comment]
`no` and `false` are equivalent with Typesafe Config AFAIK.

I just changed my value to `false` and no difference.

**Comment by marcospereira** [comment]
Hum, looks like `initializationFailFast` won't fix this issue because evolutions are requiring a connection, which is forcing HikariCP to initialize and then fail if database is not available. I don't know if HikariCP can handle this situation all by itself, but I suspect it cannot.

**Comment by huntc** [comment]
Thanks @marcospereira - you appear to be correct. I've now raised a separate issue as I see this as a hole in the behaviour of evolutions: https://github.com/playframework/playframework/issues/4675

**Comment by vrcod** [comment]
So does this mean it's impossible to use evolutions with Play/Slick combination? If that is the case that would be a serious step back.

**Comment by dotta** [comment]
@vrcod https://www.playframework.com/documentation/2.4.x/PlaySlick#Support-for-Play-database-evolutions

**Comment by vrcod** [comment]
@dotta I've added these dependencies, but the problem still persists - I'm getting "SQLTimeoutException: Timeout after 1001ms of waiting for a connection" error.

**Comment by dotta** [comment]
@vrcod The issue described in this ticket is very specific, and it was answered by @jroper in https://github.com/playframework/playframework/issues/4675. The only resemblance is that you are getting a connection timeout, but I'm skeptical you are hitting the same problem. 

If you seek help, I'd suggest to ask your question in the [playframework mailing list](https://groups.google.com/forum/#!forum/play-framework). However, please make an effort to be polite as the aggressive tone you have used [here](https://github.com/playframework/play-slick/issues/275#issuecomment-157059397) won't help you get a faster answer.

**Comment by dsounded** [comment]
Any updates ?

**Comment by dotta** [comment]
@dsounded This is an invalid (and closed) ticket, so I'm not sure what kind of update you are looking for. Please, ask usage questions in the [playframework mailing list](https://groups.google.com/forum/#!forum/play-framework). Thanks!
