### ISSUE TITLE
Could not find a suitable constructor in play.api.libs.ws.ning.NingWSPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.

### ISSUE THREAD

**Issue by pallavinagaraj01** [playframework/play-slick#362]
Could not find a suitable constructor in play.api.libs.ws.ning.NingWSPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at play.api.libs.ws.ning.NingWSPlugin.class(NingWS.scala:490)
  while locating play.api.libs.ws.ning.NingWSPlugin

1 error]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.6.jar:2.4.6]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.6.jar:2.4.6]
        at scala.util.Success.flatMap(Try.scala:231) ~[scala-library-2.11.7.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.6.jar:2.4.6]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.7.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.7.jar:na]
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in play.api.libs.ws.ning.NingWSPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at play.api.libs.ws.ning.NingWSPlugin.class(NingWS.scala:490)
  while locating play.api.libs.ws.ning.NingWSPlugin

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.6.jar:2.4.6]
        at play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:89) ~[play_2.11-2.4.6.jar:2.4.6]
        at play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:87) ~[play_2.11-2.4.6.jar:2.4.6]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]
        at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.7.jar:na]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:na]

Everything seems to be fine. Not sure the cause of the error. 
build.sbt has lib dependency 
  "com.typesafe.play" %% "play-ws" % "2.3.7",
  "com.tzavellas" % "sse-guice" % "0.7.1"

**Comment by dotta** [comment]
And how/why would this be an issue in play-slick? Please, use the playframework mailing list for questions.
