### ISSUE TITLE
NullPointerException in HasDatabaseConfig

### ISSUE THREAD

**Issue by njouanin** [playframework/play-slick#403]
Hi,
I’m evaluating play 2.6 on a project, currently `2.6.0-RC2`. I’m also using `play-slick 3.0.0-RC1`. When I run the first controller call, I get the following error :
```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at auth.services.daos.UserEntityDaoImpl.<init>(UserEntityDao.scala:30)
  while locating auth.services.daos.UserEntityDaoImpl
  while locating auth.services.daos.UserEntityDao
    for the 1st parameter of auth.services.UserServiceImpl.<init>(UserServiceImpl.scala:29)
  while locating auth.services.UserServiceImpl
  while locating auth.services.UserService
    for the 1st parameter of auth.SilhouetteModule.provideEnvironment(SilhouetteModule.scala:93)
```
As I understand, the database configuration fails to be injected. Can anyone help.
NPE is thrown from this class : https://gitlab.com/NicolasJouanin/beerfactory/blob/refactoring/backend/app/auth/services/daos/UserEntityDao.scala
the application.conf is : https://gitlab.com/NicolasJouanin/beerfactory/blob/refactoring/backend/conf/application.conf

stacktrace shows:
```
Caused by: java.lang.NullPointerException
    at play.api.db.slick.HasDatabaseConfig.profile(DatabaseConfigProvider.scala:155)
    at play.api.db.slick.HasDatabaseConfig.profile$(DatabaseConfigProvider.scala:155)
    at auth.services.daos.UserEntityDaoImpl.profile$lzycompute(UserEntityDao.scala:30)
    at auth.services.daos.UserEntityDaoImpl.profile(UserEntityDao.scala:30)
    at auth.services.daos.UserEntityDaoImpl.profile(UserEntityDao.scala:30)
    at auth.services.daos.entities.UserEntitySchema.$init$(UserEntity.scala:34)
    at auth.services.daos.UserEntityDaoImpl.<init>(UserEntityDao.scala:31)
```

**Comment by njouanin** [comment]
Found by myself. The `UserEntityDaoImpl` was declared as : 
```
class UserEntityDaoImpl @Inject()(protected val dbConfigProvider: DatabaseConfigProvider)(
    implicit executionContext: ExecutionContext)
    extends UserEntityDao
    with UserEntitySchema with HasDatabaseConfigProvider[JdbcProfile] {...}
```

The error disappear when the `HasDatabaseConfigProvider` trait is heritated first : 
```
class UserEntityDaoImpl @Inject()(protected val dbConfigProvider: DatabaseConfigProvider)(
    implicit executionContext: ExecutionContext)
    extends HasDatabaseConfigProvider[JdbcProfile]
    with UserEntityDao
    with UserEntitySchema { ... }
```
