### ISSUE TITLE
Using `withTransaction` does not close database connection

### ISSUE THREAD

**Issue by randreucetti** [playframework/play-slick#406]
Hi,

I'm currently in the process of implementing Slick for an upcoming project, however much of the older project will remain written using Anorm. Because of this I am still making use of functions such as `database.withConnection` and `database.withTransaction`

However when using my application I am seeing frequent errors around the connection pool timing out and having no available connections. 
```
Caused by: java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:18)
	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:57)
	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.withTransaction(DBApiAdapter.scala:79)
```

While looking for the problem I saw that https://github.com/playframework/play-slick/blob/master/src/evolutions/src/main/scala/play/api/db/slick/evolutions/internal/DBApiAdapter.scala#L78 fails to close the connection within function `withTransaction` and this seemed to be the source of my problem.

I have a workaround where I extend `play.api.db.Database` to close the connection in the finally box and I'm wondering should I make a PR for this or am I missing anything towards why this connection is not closed?

**Comment by marcospereira** [comment]
Closed by #407.
