### ISSUE TITLE
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast

### ISSUE THREAD

**Issue by MeerKatDev** [playframework/play-slick#443]
Not sure where I should post this, in case I am on the wrong forum please let me know. I just updated my project to Play 2.7.0-M4, but I can't run it because upon connection to the db, this appears:

```
java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:44)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:21)
        at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:47)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig(JdbcBackend.scala:287)
        at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig$(JdbcBackend.scala:284)
        at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:32)
        at slick.jdbc.JdbcBackend.createDatabase(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend.createDatabase$(JdbcBackend.scala:35)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:516)
        at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:516)
        at slick.basic.DatabaseConfig$$anon$1.db$lzycompute(DatabaseConfig.scala:103)
        at slick.basic.DatabaseConfig$$anon$1.db(DatabaseConfig.scala:102)
        at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.$anonfun$registerDatabaseShutdownHook$3(SlickApi.scala:99)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.$anonfun$registerDatabaseShutdownHook$2(SlickApi.scala:99)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I know this method was deprecated already, and I am not sure whether this is wanted and I am doing something wrong or it is some leftover from the milestone being introduced. What version of play-slick should I use with play 2.7.0-M4? I have tried 3.2.2 and 3.2.3 but the result is the same.

**Comment by marcospereira** [comment]
Related to https://github.com/slick/slick/pull/1932.

**Comment by dwijnand** [comment]
Fixed with #457, @renatocaval / @marcospereira ?

**Comment by renatocaval** [comment]
yes, correct! 

Closing...

**Comment by franbulax** [comment]
Do I have to go to Play 2.7 to rid myself of this problem?  It is preventing the deployment of a production application.

I get it on play 2.6.21 with play-slick 3.03.
Also on play 2.6.12 with play-slick 3.03, and play-slick 3.0.0

I have tried explicitly specifying HikariCP at 2.7.9 as suggested over at the slick site (https://github.com/slick/slick/issues/1963)

Is there a combination of play 2.6, hikariCP and play-slick that works?

I can't understand why it suddenly broke without my having touched my build.sbt or my plugins.sbt.

**Comment by renatocaval** [comment]
@franbulax, you need to check which Hikari version is being pulled and by which library. I believe it also depends on how you create the DB. Have you changed the way you create the Slick Database?

**Comment by franbulax** [comment]
@renatocaval 
Renato,

Thanks for jumping in here, I really appreciate it!

In fact I do not create the DB with Slick -- it's a database that predates the application.

If I interpret this correctly (I have never really had to debug anything like this before, so I'm not exactly sure) , it looks like I'm getting play-slick 3.0.0 (as requested in my build.sbt).
I'm guessing that then gets slick 3.2.0
which in turn gets hikaricp 3.2.0

I'm not really sure, though.

So, assuming that these are somehow incompatible, what I would be grateful for advice on is how to find out what combination is compatible and how to get them included at the right levels.
`
[info] Resolving com.typesafe.play#play-slick_2.12;3.0.0 ...
[info] Resolving com.typesafe.slick#slick_2.12;3.2.0 ...
[info] Resolving com.typesafe.slick#slick-hikaricp_2.12;3.2.0 
`

I had kinda hoped that by just including play-slick, I would get compatible libraries that would just work.  Are my expectations misplaced?

Thanks again for any insight you may be able to offer.

**Comment by franbulax** [comment]
@renatocaval 
Thanks for your speedy response!

Here's the relevant portion of my build.sbt

    libraryDependencies ++= Seq(jdbc, ehcache, ws, specs2 % Test, guice,
    "com.typesafe.play" %% "play-slick" % "3.0.3",
    "org.postgresql" % "postgresql" % "9.3-1102-jdbc41",

I see that I have com.zaxxer:HikariCP:2.7.9:jar in the classpath.  I'm assuming that it got there as a transitive dependency.

How I create the database?

Well, I'm not 100% sure what feature of that might be important -- I more-or-less just did monkey-see, monkey-do based on the Slick documentation.

Here's what dies:
    
    class RbacDao @Inject()(protected val dbConfigProvider: DatabaseConfigProvider)(implicit executionContext: ExecutionContext) extends HasDatabaseConfigProvider[JdbcProfile] {

    class Clients(tag: Tag) extends Table[(Long, String, Option[String], String)](tag, Some("security"), "clients") {
    def id = column[Long]("id", O.PrimaryKey)

    def name = column[String]("name")

    def description = column[Option[String]]("description")

    def clientType = column[String]("client_type")

    def * = (id, name, description, clientType)
    }
    def getClients: Future[Seq[Client]] = {
    val clients = TableQuery[Clients]
    val cl = for {
      u <- clients.sortBy(_.name)
    } yield (u.id, u.name)

    val f = db.run(cl.result)
    f.map { k => k.map { c => Client(c._1, c._2) } }
    }

Here's the definition of the `Clients` table:


       Column    |         Type          |                   Modifiers
    -------------+-----------------------+------------------------------------------------
     id          | bigint                | not null
     name        | text                  | not null
    description | text                  |
    client_type | character varying(10) | not null default 'provider'::character varying
    Indexes:
        "clients_pkey" PRIMARY KEY, btree (id)

I hope I've managed to get at the heart of what might be causing my difficulty!

**Comment by franbulax** [comment]
Here's the stack trace, down to my code (which is the `db.run(cl.result)` line 143)

    Uncaught error from thread [application-akka.actor.default-dispatcher-7]: 
    com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V, shutting down JVM since 'akka.jvm-exit-on- fatal-error' is enabled for ActorSystem[application]
    java.lang.NoSuchMethodError: com.zaxxer.hikari.HikariConfig.setInitializationFailFast(Z)V
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:44)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:21)
	at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:47)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig(JdbcBackend.scala:287)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig$(JdbcBackend.scala:284)
	at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:32)
	at slick.jdbc.JdbcBackend.createDatabase(JdbcBackend.scala:35)
	at slick.jdbc.JdbcBackend.createDatabase$(JdbcBackend.scala:35)
	at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:516)
	at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:516)
	at slick.basic.DatabaseConfig$$anon$1.db$lzycompute(DatabaseConfig.scala:103)
	at slick.basic.DatabaseConfig$$anon$1.db(DatabaseConfig.scala:102)
	at play.api.db.slick.HasDatabaseConfig.db(DatabaseConfigProvider.scala:159)
	at play.api.db.slick.HasDatabaseConfig.db$(DatabaseConfigProvider.scala:159)
	at dao.IsaacRbacDao.db(RbacDao.scala:15)
	at dao.IsaacRbacDao.getClients(RbacDao.scala:143)

**Comment by franbulax** [comment]
@renatocaval 
Thanks for your help!

This appears to have been something nutty to do with Intellij, ivy and who knows what else.
I cloned the repo again, and created a new Intellij project and presto, the problem went away.

Thank you again for your kindness and patience!
