### ISSUE TITLE
At 5.0.0, Samples don't work

### ISSUE THREAD

**Issue by kojustin** [playframework/play-slick#535]
I cloned the repository and checked out tag "5.0.0". I have no local changes. None of the sample work.

```
bash-3.2$ uname -a
Darwin MBP2012.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

basic-sample fails on the first request with
```
[basic-sample] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[error] p.a.h.DefaultHttpErrorHandler -

! @7eeoml55h - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[RuntimeException: No application loader is configured. Please configure an application loader either using the play.application.loader configuration property, or by depending on a module that configures one. You can add the Guice support module by adding "libraryDependencies += guice" to your build.sbt.]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:210)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:141)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:296)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1261)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
Caused by: java.lang.RuntimeException: No application loader is configured. Please configure an application loader either using the play.application.loader configuration property, or by depending on a module that configures one. You can add the Guice support module by adding "libraryDependencies += guice" to your build.sbt.
	at scala.sys.package$.error(package.scala:27)
	at play.api.ApplicationLoader$.play$api$ApplicationLoader$$loaderNotFound(ApplicationLoader.scala:51)
	at play.api.ApplicationLoader$.apply(ApplicationLoader.scala:159)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:188)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:181)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:141)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:296)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1261)
```

computer-database-sample fails to apply the evolution. After clicking the "Apply this script now" button I end up at the same place.
```
[computer-database-sample] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[error] p.a.h.DefaultHttpErrorHandler -

! @7eeompa5i - Internal server error, for (GET) [/] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$5(ApplicationEvolutions.scala:523)
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$5$adapted(ApplicationEvolutions.scala:516)
	at play.api.db.evolutions.ApplicationEvolutions$.$anonfun$runEvolutions$1(ApplicationEvolutions.scala:208)
	at play.api.db.evolutions.ApplicationEvolutions$.withLock(ApplicationEvolutions.scala:229)
	at play.api.db.evolutions.ApplicationEvolutions$.runEvolutions(ApplicationEvolutions.scala:199)
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$4(ApplicationEvolutions.scala:516)
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$4$adapted(ApplicationEvolutions.scala:511)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at play.api.db.evolutions.EvolutionsWebCommands.handleWebCommand(ApplicationEvolutions.scala:511)
	at play.core.DefaultWebCommands.$anonfun$handleWebCommand$1(WebCommands.scala:41)

--- (RELOAD) ---

[error] p.a.h.DefaultHttpErrorHandler -

! @7eeompnmp - Internal server error, for (GET) [/] ->

play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$5(ApplicationEvolutions.scala:523)
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$5$adapted(ApplicationEvolutions.scala:516)
	at play.api.db.evolutions.ApplicationEvolutions$.$anonfun$runEvolutions$1(ApplicationEvolutions.scala:208)
	at play.api.db.evolutions.ApplicationEvolutions$.withLock(ApplicationEvolutions.scala:229)
	at play.api.db.evolutions.ApplicationEvolutions$.runEvolutions(ApplicationEvolutions.scala:199)
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$4(ApplicationEvolutions.scala:516)
	at play.api.db.evolutions.EvolutionsWebCommands.$anonfun$handleWebCommand$4$adapted(ApplicationEvolutions.scala:511)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at play.api.db.evolutions.EvolutionsWebCommands.handleWebCommand(ApplicationEvolutions.scala:511)
	at play.core.DefaultWebCommands.$anonfun$handleWebCommand$1(WebCommands.scala:41)
```

streams-sample fails with 
```
[computer-database-sample] $ project streams-sample
[info] Set current project to iteratee-sample (in build file:/Users/kostar/Downloads/play-slick/)
[iteratee-sample] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[debug] s.j.J.statement - Preparing statement: select count(1) from "RECORDS"
[error] p.a.h.DefaultHttpErrorHandler -

! @7eeon438f - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "RECORDS" not found; SQL statement:
select count(1) from "RECORDS" [42102-200]
  at modules.InitialData.<init>(InitialData.scala:20)
  at modules.InitialDataModule.configure(InitialData.scala:15) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.InitialDataModule)
  while locating modules.InitialData

1 error]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:210)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:141)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:296)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1261)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:624)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:501)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "RECORDS" not found; SQL statement:
select count(1) from "RECORDS" [42102-200]
  at modules.InitialData.<init>(InitialData.scala:20)
  at modules.InitialDataModule.configure(InitialData.scala:15) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.InitialDataModule)
  while locating modules.InitialData

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:189)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "RECORDS" not found; SQL statement:
select count(1) from "RECORDS" [42102-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableOrView(Parser.java:7628)
	at org.h2.command.Parser.readTableFilter(Parser.java:1970)
	at org.h2.command.Parser.parseSelectFromPart(Parser.java:2827)
	at org.h2.command.Parser.parseSelect(Parser.java:2959)
	at org.h2.command.Parser.parseQuerySub(Parser.java:2817)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2649)
```

**Comment by kojustin** [comment]
Adding guice to the basic-sample as a dependency doesn't fix it. It now fails the same way computer-database-sample fails.

**Comment by renatocaval** [comment]
@kojustin, thanks for reporting it. 

It seems that the master branch is also failing, which indicates that none of those are being tested in CI. 

We should remove the samples here and point users to https://github.com/playframework/play-samples. There are two Slick samples there and should be enough to give a good start.

Doesn't make sense to have unmaintained samples.

**Comment by kojustin** [comment]
I tried doing building a "dist" package, unpacking it, and then running that. *That* worked correctly, so it appears that it is just the "run" in sbt that is not working.

**Comment by renatocaval** [comment]
Interesting. I may be something related with the sbt version then.

**Comment by Max-AR** [comment]
https://github.com/playframework/play-samples/pull/153

**Comment by Max-AR** [comment]
@kojustin A number of contributors have been working on this one and I've tested the slick examples and they all work as they say on the tin. 

Are you happy for us to close this one?
